project:
  type: website
  render:
    - "*.qmd"
    - "!Dunnet_vs_Holm/"
    - "!exponential-glm-coverage/"
    - "!lmer-slopes-new/"
    - "!lmer_vs_slope-t-test/"
    - "!post-with-code/"
    - "!R2-in-CV/"
    - "!T-test_vs_Wilcoxon/"

website:
  title: "Lukas Graz"
  page-footer: "Copyright 2024, Lukas Graz" 
  repo-url: https://lgraz.github.io
  repo-actions: [edit, source, issue]
  navbar:
    right:
      - CV.qmd
      - icon: github
        href: https://github.com/LGraz
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/lukas-graz/
format:
  html:
    theme: cosmo
    css: styles.css

