project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Lukas Graz"
  page-footer: "Lukas Graz, Funkwiesenstrasse 81, 8050 ZÃ¼rich, [stat.consulting.graz@gmail.com](mailto:stat.consulting.graz@gmail.com)" 
  repo-url: https://github.com/LGraz/LGraz.github.io/
  repo-actions: [edit, source, issue]
  navbar:
    right:
      # - CV.qmd
      - statistical-consulting.qmd
      - icon: github
        href: https://github.com/LGraz
      - icon: linkedin
        # text: LinkedIn #
        href: https://www.linkedin.com/in/lukas-graz/
format:
  html:
    theme: cosmo
    css: styles.css

